export component MainWindow inherits Window {
    title: "Hello Tray";
    width: 300px;
    height: 100px;

    callback quit();
    callback triggered;

    Text {
        text: "Hello, World!";
        horizontal-alignment: center;
        vertical-alignment: center;
    }

    Timer {
        interval: 100ms;
        running: true;
        triggered => {
            root.triggered();
        }
    }
}
